### ISSUE TITLE
No option "Push Button" or WPS Push Button, in Wi-Fi Network 

### ISSUE THREAD

**Issue by masshuvo** [stryker-project/app#10]
This is a very important function for WiFi penetration tester. 

Push Button This option is not kept it should have been given.

![Screenshot_2023-06-16-23-24-53-219_com zalexdev stryker](https://github.com/stryker-project/app/assets/108648096/4b1d6227-95a7-4494-9a52-f9e9d00a3170)

Like that: 

![Screenshot_2023-06-16-23-26-16-953-edit_com offsec nethunter](https://github.com/stryker-project/app/assets/108648096/c9b345a7-6ca5-4660-b2d6-9af912656601)

**Comment by stryker-project** [comment]
added in todo list

**Comment by masshuvo** [comment]
If I can't get the GUI version of it, I have to download and use OneShot tools separately?
