### ISSUE TITLE
Pin brute force attack stuck at 04190004

### ISSUE THREAD

**Issue by yin2hao** [stryker-project/app#15]
Pin brute force attack stuck at 04190004, regardless of hidden Mac, device is MediaTek，stryker 5b90(1)
![Screenshot_2024-08-14-10-34-39-11_a36489171003e213fadb275961fc67f8](https://github.com/user-attachments/assets/b1c8e8a5-605a-4dbc-b20b-fc9e1edb2aab)

**Comment by zalexdev** [comment]
This primarily happens when the WIFI network is blocking device mac because of the attack

**Comment by yin2hao** [comment]
> This primarily happens when the WIFI network is blocking device mac because of the attack

I have the impression that the router either does not return the result of the wifi pin or returns it with delay. Why would you block your device Mac 04190004? Is there any special meaning to 0419004. Not only me, but also my friends have had this problem
Or, if the developer is considering adding a function that starts with a specified PIN code?
And thank you for the answer
