### ISSUE TITLE
loadibg core

### ISSUE THREAD

**Issue by zoioz** [stryker-project/app#7]
![Screenshot_20220711-202644](https://user-images.githubusercontent.com/83503711/178270017-d994d042-1966-4485-994b-97a85b6880e5.png)

i can`t download core.what should  i do ?

**Comment by stryker-project** [comment]
Use vpn, or manual installation.
Manual (use SU terminal):

wget https://github.com/stryker-project/stryker-chroot/releases/download/2.0R/Stryker2R.tar.gz
mkdir /data/local/stryker
busybox tar -xf Stryker2R.tar.gz -C /data/local/stryker
